
services:
  sqlserver:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "L2tecnologia@"
      ACCEPT_EULA: "YES"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

volumes:
  sql_data:

networks:
  backend: